version: '3.8'

services:
  telegram-bot:
    build: .
    container_name: wireguard-bot
    restart: unless-stopped
    volumes:
      - ./configs:/app/configs
      - ./data:/app/data
    env_file:
      - .env